### ISSUE TITLE
Address Trees as Trees (vs Shrubs) Protocol Change

### ISSUE THREAD

**Issue by blcampbell-NCPN** [NCPN/upland#85]
Address the picklist (drop-down listbox) logic so that trees (JUNOST, PINE??) are considered trees. This reverts much (all?) of the work from 2016 changes related to these drop-downs. [Edit: Only JUNOST/PINEDU are reverted.]

**Comment by hmthomas** [comment]
I am not able to edit the description, but I would suggest updating it to say something like "Remove Juniperus osteosperma (JUNOST) and Pinus edulis (PINEDU) from the 1-meter belt shrub species pick list. These are non-shrub (tree) species that were previously included in the shrub pick list because they were treated as shrubs. With the recent change to the protocol, JUNOST and PINEDU will be treated as trees, so they should be removed from the shrub pick list." 

And BTW, this only reverts a small portion of the 2016 changes  to the drop-downs. Most of your previous effort will not be wasted!

**Comment by blcampbell-NCPN** [comment]
Revises union query to remove PINEDU & JUNOST species.
Only this section of the union is removed. Other updates from 2016 remain unchanged.

**Comment by blcampbell-NCPN** [comment]
Remove Pinus edulis, P. monophylla, and Juniperus osteosperma from shrub density plant list.
